require('user.plugins')
require('user.options')
require('user.keymaps')
require('user.colorscheme')

require('user.autopairs')
require('user.comment')
require('user.cmp')
require('user.gitsigns')
require('user.lsp')
require('user.telescope')
require('user.treesitter')
